name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: pipx install uv

      - name: Setup Python environment
        run: uv sync

      - name: Install ruff
        run: uv add --dev ruff

      - name: Check formatting and linting
        run: |
          uv run ruff check .
          uv run ruff format --check .